[package]
name = "csm-checker"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4"
actix-files = "0.6"
chrono = { version = "0.4", features = ["serde"] }
ureq = { version = "2", features = ["json"] }

[dependencies.serde]
version = "1"
features = ["derive"]
